services:
  selenium:
    container_name: netflix_watcher_selenium
    image: seleniarm/standalone-chromium:latest
    restart: on-failure:5
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: netflix_watcher_app
    restart: on-failure:5
    env_file:
      - ./.env
