name: Lint

on:
  push:
    branches:
      - '*'  # Run on all branches

jobs:
  lint:
    name: Run Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Start services
        run: make up

      - name: Wait for app service to be ready
        run: sleep 10  # Adjust the sleep duration as needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Run linting
        run: |
          make lint
